"""Deterministic code routing of the gated lens evidence onto THE SPLIT.

The SPLIT synthesis is a set of *fixed routing rules* (see ``prompts.SPLIT_SYSTEM``):
each axis reads one lens's evidence signature and maps it to a cell state. Those rules
are deterministic, so they can be applied in code — which is strictly more reliable than
asking an 8B model to emit a four-cell schema-valid JSON object every time.

Honest division of labour: the IBM models do the hard natural-language work — each lens
READING is generated by Granite and audited by Granite Guardian — while the routing of
those gated readings onto the four axes is **always** this deterministic code, in both the
live and the offline bake. We do not ask the 8B model to emit the four-cell SPLIT schema;
it routinely fails it, and the routing rules are fixed anyway, so code is both faithful to
the documented rules and reliable. The router is **not** hard-coded toward any answer: it
reads only the lens signatures, so a different incident (e.g. Lampard) yields a different
SPLIT — the exact property the thesis oracle checks.

Each axis maps from exactly one lens's gated output:

* RULE_AMBIGUITY        ← REFEREE   (SUPPORTS=clear law → ABSENT; DISPUTES=competing
                                     clauses → PRESENT; MIXED=one edge → WEAK)
* INDETERMINACY         ← admitted act → ABSENT; else HISTORICAL stance DISPUTES (the truth
                                     is unrecoverable even now) → PRESENT; else NOT_DOCUMENTED.
                                     Keyed on the model's real stance, never a planted id.
* DECISION_TIME_DEFICIT ← HISTORICAL(SUPPORTS=tech absent + view obstructed → PRESENT;
                                     DISPUTES=truth unrecoverable → ABSENT, that is the
                                     indeterminacy case; MIXED=info fully adequate → ABSENT)
* CULTURAL_PRIOR_BIAS   ← FRAMING   (MIXED=opposed named sources → PRESENT;
                                     SUPPORTS/DISPUTES one-sided → ABSENT)
"""

from __future__ import annotations

from offside_engine.analyze.split_schema import (
    CellState,
    LensOutput,
    Split,
    SplitCell,
)

# Does the SHARED_SETTLED_FACT record the actor admitting the act? Passed in by the bake
# so the INDETERMINACY precondition can fire without re-reading sources.


def _by_lens(lenses: list[LensOutput]) -> dict[str, LensOutput]:
    return {lo.lens: lo for lo in lenses}


def _cell(axis, state: CellState, source: LensOutput | None, rationale: str) -> SplitCell:
    cite = list(source.citation_ids) if (source and state in ("PRESENT", "WEAK")) else []
    return SplitCell(axis=axis, state=state, citation_ids=cite, rationale=rationale)


def _grounded(lo: LensOutput | None) -> bool:
    return bool(lo and lo.state == "GROUNDED" and lo.citation_ids)


# The HISTORICAL lens answers two physically different questions about the SAME incident
# and reports them as two distinct stances Granite actually emits:
#
#   SUPPORTS  — "the truth was knowable in principle but unavailable to the officials in
#               the moment" (no review tech, obstructed view). -> a DECISION-TIME deficit.
#   DISPUTES  — "the exact truth is not recoverable even with all current technology"
#               (irreducible measurement at the margin; the authorities apply a thicker
#               tolerance line). -> INDETERMINACY.
#
# INDETERMINACY is keyed on the model's DISPUTES stance — a genuine reading of the
# evidence — NOT on any author-planted citation id. The two HISTORICAL meanings stay
# cleanly separable because they are two different stances, not two greps. This is the
# whole reason the axis is honest: feed the lens different evidence and Granite picks a
# different stance, which routes to a different axis — the router never inspects ids.


def _signals_measurement_indeterminacy(lo: LensOutput | None) -> bool:
    """The HISTORICAL lens DISPUTES knowability — i.e. it read the evidence as 'the exact
    truth is not recoverable even now', the indeterminacy signal, as opposed to SUPPORTS
    (a decision-time gap). A real model stance, audited by Guardian like any other."""
    return bool(lo) and lo.stance == "DISPUTES"


def _basis(lo: LensOutput | None) -> str:
    """A short, incident-specific clause drawn from the governing lens's own grounded
    rationale, used to give a ruled-out / not-documented cell face an incident-specific
    reason instead of a constant. The lens rationale is already citation-grounded and
    incident-specific, so this keeps the router deterministic while ending the verbatim
    repetition of the same ruled-out sentence across every incident.

    We take the first clause (up to the first ';' or '.') and lower-case its lead so it
    reads as a continuation. Empty/insufficient lenses yield '' (caller falls back).
    """
    if not lo or not lo.rationale:
        return ""
    first = lo.rationale.replace("\n", " ").strip()
    for sep in (";", ". "):
        idx = first.find(sep)
        if idx != -1:
            first = first[:idx]
            break
    first = first.strip().rstrip(".")
    if not first:
        return ""
    return first[0].lower() + first[1:]


def _present_rationale(lo: LensOutput, fallback: str) -> str:
    """The rationale to attach to a PRESENT/WEAK cell.

    A PRESENT/WEAK cell is re-audited by Granite Guardian against the SAME cited passages the
    lens used. A generic template sentence ("technology was absent...") is not faithful to the
    specific passage text and Guardian rightly flags it UNGROUNDED — silently demoting a cell
    that is in fact well-grounded. So we carry the LENS's own rationale onto the cell: it was
    already audited GROUNDED against those exact passages at the lens stage, so the cell-stage
    audit sees faithful, grounded text and the cell survives. Falls back to the template only
    if the lens somehow has no rationale.
    """
    r = (lo.rationale or "").strip()
    return r if r else fallback


def derive_split(lenses: list[LensOutput], *, admitted_act: bool) -> Split:
    """Route the gated lens outputs onto the four-axis SPLIT by the fixed rules."""
    by = _by_lens(lenses)
    ref = by.get("REFEREE")
    hist = by.get("HISTORICAL")
    fram = by.get("FRAMING")

    # RULE_AMBIGUITY ← REFEREE. A clear single offence clause (SUPPORTS) rules it out;
    # genuinely competing clauses (DISPUTES) make it present; a single edge is weak.
    if not _grounded(ref):
        rule = _cell("RULE_AMBIGUITY", "NOT_DOCUMENTED", None,
                     "No referee-law evidence bears on this incident.")
    elif ref.stance == "DISPUTES":
        rule = _cell("RULE_AMBIGUITY", "PRESENT", ref,
                     _present_rationale(ref, "Retrieved clauses point to different outcomes for the same facts."))
    elif ref.stance == "MIXED":
        rule = _cell("RULE_AMBIGUITY", "WEAK", ref,
                     _present_rationale(ref, "The retrieved law is mostly clear but one edge is underspecified."))
    else:  # SUPPORTS — a clear single offence clause
        basis = _basis(ref)
        rule = _cell("RULE_AMBIGUITY", "ABSENT", None,
                     f"A clear single clause governs the act — {basis}." if basis
                     else "A clear single offence clause governs the act, with no competing clause.")

    # INDETERMINACY — is the decisive truth itself unrecoverable? Gated by the admission
    # precondition first (an admitted act resolves any residual and dominates). Otherwise
    # it fires on the HISTORICAL lens's DISPUTES stance — Granite's own reading that the
    # exact truth is not recoverable even with current technology (the semi-automated
    # offside "thicker line" case), as opposed to its SUPPORTS stance (a decision-time
    # gap). The signal is a real model stance audited by Guardian, never an author-planted
    # citation id. Independent of the REFEREE stance: rule ambiguity (competing clauses) is
    # NOT the truth being unknowable, so a DISPUTES referee reading must not leak here.
    if admitted_act:
        indet = _cell("INDETERMINACY", "ABSENT", None,
                      "The act is admitted, so the deliberateness residual is resolved.")
    elif _grounded(hist) and _signals_measurement_indeterminacy(hist):
        indet = _cell("INDETERMINACY", "PRESENT", hist,
                      _present_rationale(hist,
                          "The fact is defined precisely by the Law but cannot be measured to "
                          "that precision in the moment — the truth at the margin is not recoverable."))
    elif _grounded(hist):
        # The historical record DOES bear on knowability and says the truth was knowable /
        # the information adequate (a SUPPORTS or MIXED reading), so indeterminacy is actively
        # RULED OUT — not merely undocumented. State and prose agree: a confident rule-out.
        basis = _basis(hist)
        indet = _cell("INDETERMINACY", "ABSENT", None,
                      f"The decisive truth is recoverable — {basis}." if basis
                      else "The evidence shows the decisive truth is recoverable; nothing makes it unknowable.")
    else:
        # No historical evidence bears on knowability either way — genuinely undocumented.
        indet = _cell("INDETERMINACY", "NOT_DOCUMENTED", None,
                      "No evidence bears on whether the decisive truth is recoverable.")

    # DECISION_TIME_DEFICIT ← HISTORICAL stance, read straight off the model's reading:
    #   SUPPORTS  -> the officials could not access the truth in the moment      -> PRESENT
    #   DISPUTES  -> the truth is unrecoverable even now (that fired INDETERMINACY) — NOT a
    #               sightline gap; better cameras in the moment would not fix it  -> ABSENT
    #   MIXED     -> the information was adequate and the truth fully knowable; the dispute
    #               is not about what could be seen at all                        -> ABSENT
    #   (insufficient) -> nothing bears on what was available                     -> NOT_DOCUMENTED
    if not _grounded(hist):
        dtd = _cell("DECISION_TIME_DEFICIT", "NOT_DOCUMENTED", None,
                    "No historical fact bears on what was available at the moment of the call.")
    elif hist.stance == "SUPPORTS":
        dtd = _cell("DECISION_TIME_DEFICIT", "PRESENT", hist,
                    _present_rationale(hist, "Resolving technology was absent and the view was obstructed in the moment."))
    elif hist.stance == "DISPUTES":
        dtd = _cell("DECISION_TIME_DEFICIT", "ABSENT", None,
                    "The technology can see the moment; the gap is that the exact truth is "
                    "unrecoverable at all — an indeterminacy, not a decision-time deficit.")
    else:  # MIXED — the information was adequate; the truth was fully knowable in the moment
        basis = _basis(hist)
        dtd = _cell("DECISION_TIME_DEFICIT", "ABSENT", None,
                    f"The decisive truth was available at the moment — {basis}." if basis
                    else "The information was adequate and the truth was fully knowable at the moment of the call.")

    # CULTURAL_PRIOR_BIAS ← FRAMING. Opposed named sources on the same fact → present.
    if not _grounded(fram):
        cult = _cell("CULTURAL_PRIOR_BIAS", "NOT_DOCUMENTED", None,
                     "No named-source quote bears on this incident.")
    elif fram.stance == "MIXED":
        cult = _cell("CULTURAL_PRIOR_BIAS", "PRESENT", fram,
                     _present_rationale(fram, "Named sources frame the same settled fact in opposed valence."))
    else:  # SUPPORTS / DISPUTES — one-sided
        basis = _basis(fram)
        cult = _cell("CULTURAL_PRIOR_BIAS", "ABSENT", None,
                     f"Named sources are one-sided — {basis}." if basis
                     else "Named sources agree on the outcome; there is no opposed framing.")

    headline = (
        "It stays contested over "
        + _name_present_axes([rule, indet, dtd, cult])
        + " — not over the dimensions ruled out."
    )
    return Split(cells=[rule, indet, dtd, cult], headline=headline)


_AXIS_PHRASE = {
    "RULE_AMBIGUITY": "whether the Law is clear",
    "INDETERMINACY": "whether the fact is knowable",
    "DECISION_TIME_DEFICIT": "what could be seen in the moment",
    "CULTURAL_PRIOR_BIAS": "how named sources frame the same fact",
}


def _name_present_axes(cells: list[SplitCell]) -> str:
    live = [_AXIS_PHRASE[c.axis] for c in cells if c.state in ("PRESENT", "WEAK")]
    if not live:
        return "no single dimension"
    if len(live) == 1:
        return live[0]
    return ", ".join(live[:-1]) + " and " + live[-1]
