"""Deterministic code routing of the gated lens evidence onto THE SPLIT.

The SPLIT synthesis is a set of *fixed routing rules* (see ``prompts.SPLIT_SYSTEM``):
each axis reads one lens's evidence signature and maps it to a cell state. Those rules
are deterministic, so they can be applied in code — which is strictly more reliable than
asking an 8B model to emit a four-cell schema-valid JSON object every time.

Honest division of labour: the IBM models do the hard natural-language work — each lens
READING is generated by Granite and audited by Granite Guardian — while the routing of
those gated readings onto the four axes is **always** this deterministic code, in both the
live and the offline bake. We do not ask the 8B model to emit the four-cell SPLIT schema;
it routinely fails it, and the routing rules are fixed anyway, so code is both faithful to
the documented rules and reliable. The router is **not** hard-coded toward any answer: it
reads only the lens signatures, so a different incident (e.g. Lampard) yields a different
SPLIT — the exact property the thesis oracle checks.

Each axis maps from exactly one lens's gated output:

* RULE_AMBIGUITY        ← REFEREE   (SUPPORTS=clear law → ABSENT; DISPUTES=competing
                                     clauses → PRESENT; MIXED=one edge → WEAK)
* INDETERMINACY         ← admitted act → ABSENT; else a HISTORICAL measurement-
                                     indeterminacy signal → PRESENT; else NOT_DOCUMENTED
* DECISION_TIME_DEFICIT ← HISTORICAL(SUPPORTS=tech absent + view obstructed → PRESENT;
                                     MIXED=one of the two → WEAK; DISPUTES → ABSENT)
* CULTURAL_PRIOR_BIAS   ← FRAMING   (MIXED=opposed named sources → PRESENT;
                                     SUPPORTS/DISPUTES one-sided → ABSENT)
"""

from __future__ import annotations

from offside_engine.analyze.split_schema import (
    CellState,
    LensOutput,
    Split,
    SplitCell,
)

# Does the SHARED_SETTLED_FACT record the actor admitting the act? Passed in by the bake
# so the INDETERMINACY precondition can fire without re-reading sources.


def _by_lens(lenses: list[LensOutput]) -> dict[str, LensOutput]:
    return {lo.lens: lo for lo in lenses}


def _cell(axis, state: CellState, source: LensOutput | None, rationale: str) -> SplitCell:
    cite = list(source.citation_ids) if (source and state in ("PRESENT", "WEAK")) else []
    return SplitCell(axis=axis, state=state, citation_ids=cite, rationale=rationale)


def _grounded(lo: LensOutput | None) -> bool:
    return bool(lo and lo.state == "GROUNDED" and lo.citation_ids)


# A HISTORICAL reading carries a MEASUREMENT-indeterminacy signal when it cites an atom
# whose bearing is "the exact truth at the margin is not recoverable". Such atoms are
# tagged with this id suffix in the historical corpus. Keying INDETERMINACY on the cited
# atom — not on a reused stance — keeps the two HISTORICAL meanings ("info was adequate"
# vs "the truth is unmeasurable") cleanly separable, so the router never conflates a
# decision-time question with an indeterminacy one.
_MARGIN_UNRECOVERABLE_SUFFIX = "-margin-unrecoverable"


def _signals_measurement_indeterminacy(lo: LensOutput | None) -> bool:
    return bool(lo) and any(
        cid.endswith(_MARGIN_UNRECOVERABLE_SUFFIX) for cid in lo.citation_ids
    )


def _basis(lo: LensOutput | None) -> str:
    """A short, incident-specific clause drawn from the governing lens's own grounded
    rationale, used to give a ruled-out / not-documented cell face an incident-specific
    reason instead of a constant. The lens rationale is already citation-grounded and
    incident-specific, so this keeps the router deterministic while ending the verbatim
    repetition of the same ruled-out sentence across every incident.

    We take the first clause (up to the first ';' or '.') and lower-case its lead so it
    reads as a continuation. Empty/insufficient lenses yield '' (caller falls back).
    """
    if not lo or not lo.rationale:
        return ""
    first = lo.rationale.replace("\n", " ").strip()
    for sep in (";", ". "):
        idx = first.find(sep)
        if idx != -1:
            first = first[:idx]
            break
    first = first.strip().rstrip(".")
    if not first:
        return ""
    return first[0].lower() + first[1:]


def derive_split(lenses: list[LensOutput], *, admitted_act: bool) -> Split:
    """Route the gated lens outputs onto the four-axis SPLIT by the fixed rules."""
    by = _by_lens(lenses)
    ref = by.get("REFEREE")
    hist = by.get("HISTORICAL")
    fram = by.get("FRAMING")

    # RULE_AMBIGUITY ← REFEREE. A clear single offence clause (SUPPORTS) rules it out;
    # genuinely competing clauses (DISPUTES) make it present; a single edge is weak.
    if not _grounded(ref):
        rule = _cell("RULE_AMBIGUITY", "NOT_DOCUMENTED", None,
                     "No referee-law evidence bears on this incident.")
    elif ref.stance == "DISPUTES":
        rule = _cell("RULE_AMBIGUITY", "PRESENT", ref,
                     "Retrieved clauses point to different outcomes for the same facts.")
    elif ref.stance == "MIXED":
        rule = _cell("RULE_AMBIGUITY", "WEAK", ref,
                     "The retrieved law is mostly clear but one edge is underspecified.")
    else:  # SUPPORTS — a clear single offence clause
        basis = _basis(ref)
        rule = _cell("RULE_AMBIGUITY", "ABSENT", None,
                     f"A clear single clause governs the act — {basis}." if basis
                     else "A clear single offence clause governs the act, with no competing clause.")

    # INDETERMINACY — is the decisive truth itself unrecoverable? Gated by the admission
    # precondition first (an admitted act resolves any deliberateness residual and
    # dominates). Otherwise it fires only on a genuine MEASUREMENT-indeterminacy signal
    # carried by the HISTORICAL lens — the fact is defined precisely by the Law but cannot
    # be measured to that precision in practice (the semi-automated-offside "thick line"
    # case). Note this is independent of the REFEREE stance: rule ambiguity (competing
    # clauses) is NOT the same as the truth being unknowable, so a DISPUTES referee reading
    # must not leak into this axis.
    if admitted_act:
        indet = _cell("INDETERMINACY", "ABSENT", None,
                      "The act is admitted, so the deliberateness residual is resolved.")
    elif _grounded(hist) and _signals_measurement_indeterminacy(hist):
        indet = _cell("INDETERMINACY", "PRESENT", hist,
                      "The fact is defined precisely by the Law but cannot be measured to "
                      "that precision in the moment — the truth at the margin is not recoverable.")
    else:
        basis = _basis(hist) if _grounded(hist) else ""
        indet = _cell("INDETERMINACY", "NOT_DOCUMENTED", None,
                      f"Nothing makes the truth unrecoverable — {basis}." if basis
                      else "No evidence makes the decisive truth unrecoverable.")

    # DECISION_TIME_DEFICIT ← HISTORICAL. Tech absent AND view obstructed → present.
    if not _grounded(hist):
        dtd = _cell("DECISION_TIME_DEFICIT", "NOT_DOCUMENTED", None,
                    "No historical fact bears on what was available at the moment of the call.")
    elif hist.stance == "SUPPORTS":
        dtd = _cell("DECISION_TIME_DEFICIT", "PRESENT", hist,
                    "Resolving technology was absent and the view was obstructed in the moment.")
    elif hist.stance == "MIXED":
        dtd = _cell("DECISION_TIME_DEFICIT", "WEAK", hist,
                    "Only one of absent technology or an obstructed view holds.")
    else:
        basis = _basis(hist)
        dtd = _cell("DECISION_TIME_DEFICIT", "ABSENT", None,
                    f"The decisive truth was available at the moment — {basis}." if basis
                    else "Review technology existed and the view was clear at the moment of the call.")

    # CULTURAL_PRIOR_BIAS ← FRAMING. Opposed named sources on the same fact → present.
    if not _grounded(fram):
        cult = _cell("CULTURAL_PRIOR_BIAS", "NOT_DOCUMENTED", None,
                     "No named-source quote bears on this incident.")
    elif fram.stance == "MIXED":
        cult = _cell("CULTURAL_PRIOR_BIAS", "PRESENT", fram,
                     "Named sources frame the same settled fact in opposed valence.")
    else:  # SUPPORTS / DISPUTES — one-sided
        basis = _basis(fram)
        cult = _cell("CULTURAL_PRIOR_BIAS", "ABSENT", None,
                     f"Named sources are one-sided — {basis}." if basis
                     else "Named sources agree on the outcome; there is no opposed framing.")

    headline = (
        "It stays contested over "
        + _name_present_axes([rule, indet, dtd, cult])
        + " — not over the dimensions ruled out."
    )
    return Split(cells=[rule, indet, dtd, cult], headline=headline)


_AXIS_PHRASE = {
    "RULE_AMBIGUITY": "whether the Law is clear",
    "INDETERMINACY": "whether the fact is knowable",
    "DECISION_TIME_DEFICIT": "what could be seen in the moment",
    "CULTURAL_PRIOR_BIAS": "how named sources frame the same fact",
}


def _name_present_axes(cells: list[SplitCell]) -> str:
    live = [_AXIS_PHRASE[c.axis] for c in cells if c.state in ("PRESENT", "WEAK")]
    if not live:
        return "no single dimension"
    if len(live) == 1:
        return live[0]
    return ", ".join(live[:-1]) + " and " + live[-1]
